/**
 * MAT-03: bank taxonomy — canonical / authored / derived / compiled.
 *
 * The schema has no dedicated taxonomy field, and adding one would require a
 * migration, validation, import/export, and test surface for a purely
 * presentational distinction. Instead this derives the taxonomy
 * deterministically from metadata `defaultProject()` already writes for
 * every canonical bank (a "Source:" / "Derived:" description prefix) plus
 * token count, per the documented rules below. User-authored banks (no
 * prefix convention) fall back to "authored".
 */

export type BankTaxonomy = "canonical" | "authored" | "derived" | "compiled";

/** Above this token count a "Derived:" bank is treated as compiled — large
 * enough that showing it as a raw list by default is unusable (MAT-01). */
const COMPILED_TOKEN_THRESHOLD = 40;

export function bankTaxonomy(desc: string | undefined, tokenCount: number): BankTaxonomy {
  const d = (desc ?? "").trim();
  const isDerived = /^derived:/i.test(d);
  if (isDerived) {
    return /\bcompiled\b/i.test(d) || tokenCount > COMPILED_TOKEN_THRESHOLD ? "compiled" : "derived";
  }
  if (/^source:/i.test(d)) return "canonical";
  return "authored";
}

export const TAXONOMY_LABEL: Record<BankTaxonomy, string> = {
  canonical: "Canonical",
  authored: "Authored",
  derived: "Derived",
  compiled: "Compiled",
};

export const TAXONOMY_HINT: Record<BankTaxonomy, string> = {
  canonical: "From the original source text, unmodified.",
  authored: "Created directly in this project.",
  derived: "Generated from other banks by a fixed rule.",
  compiled: "Generated by combining many source values into a large set — shown as a summary first.",
};
